"""
Metadata extraction service.
Supports images (EXIF), audio, video, PDF, and DOCX files.
"""
import io
import os
import struct
import zipfile
from pathlib import Path
from typing import List, Tuple
from xml.etree import ElementTree as ET

from app.models.analysis import MetadataField

# Known AI-generation software strings
AI_SOFTWARE_MARKERS = [
    "midjourney", "dall-e", "dall·e", "stable diffusion", "diffusion",
    "adobe firefly", "generative", "runway", "pika", "kling", "sora",
    "elevenlabs", "whisper", "bark", "audiogen", "musicgen",
    "novelai", "invokeai", "automatic1111", "comfyui", "fooocus",
    "dreamstudio", "nightcafe", "artbreeder",
    "python-docx", "generated by python-docx",
    # LLM / chat AI platforms
    "chatgpt", "openai", "gpt-4", "gpt-3", "gpt4", "gpt3",
    "claude", "anthropic", "gemini", "copilot",
    "weasyprint", "puppeteer",  # headless renderers used by AI platforms
]

NEUTRAL_SOFTWARE = [
    "adobe photoshop", "lightroom", "capture one", "luminar",
    "gimp", "affinity photo", "darktable", "rawtherapee",
]


def _flag_software(value: str) -> Tuple[bool, str]:
    low = value.lower()
    for marker in AI_SOFTWARE_MARKERS:
        if marker in low:
            return True, f"AI generation tool detected: '{value}'"
    return False, ""


async def extract_metadata(file_path: Path, mime_type: str) -> List[MetadataField]:
    fields: List[MetadataField] = []

    if mime_type.startswith("image/"):
        fields = await _extract_image_metadata(file_path)
    elif mime_type.startswith("audio/"):
        fields = await _extract_audio_metadata(file_path)
    elif mime_type.startswith("video/"):
        fields = await _extract_video_metadata(file_path)
    elif mime_type == "application/pdf":
        fields = await _extract_pdf_metadata(file_path)
    elif mime_type in (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/msword",
    ):
        fields = await _extract_docx_metadata(file_path)

    # Always include basic file stats
    stat = file_path.stat()
    fields.insert(0, MetadataField(key="File Size", value=f"{stat.st_size:,} bytes"))
    fields.insert(1, MetadataField(key="MIME Type", value=mime_type))

    return fields


async def _extract_image_metadata(file_path: Path) -> List[MetadataField]:
    fields: List[MetadataField] = []
    try:
        import exifread
        with open(file_path, "rb") as f:
            tags = exifread.process_file(f, details=False)

        if not tags:
            fields.append(MetadataField(
                key="EXIF Data",
                value="None found",
                suspicious=True,
                note="Missing EXIF is common in AI-generated images; cameras always embed metadata"
            ))
            return fields

        key_map = {
            "Image Make": "Camera Make",
            "Image Model": "Camera Model",
            "Image Software": "Software",
            "EXIF DateTimeOriginal": "Date Taken",
            "EXIF DateTimeDigitized": "Date Digitized",
            "Image DateTime": "Date Modified",
            "EXIF ExposureTime": "Exposure Time",
            "EXIF FNumber": "F-Number",
            "EXIF ISOSpeedRatings": "ISO Speed",
            "EXIF FocalLength": "Focal Length",
            "GPS GPSLatitude": "GPS Latitude",
            "GPS GPSLongitude": "GPS Longitude",
            "Image XResolution": "X Resolution",
            "Image YResolution": "Y Resolution",
            "EXIF ColorSpace": "Color Space",
            "EXIF Flash": "Flash",
            "Image Orientation": "Orientation",
            "EXIF LensModel": "Lens Model",
            "EXIF ExifImageWidth": "Image Width",
            "EXIF ExifImageLength": "Image Height",
        }

        found_camera = False
        found_gps = False

        for exif_key, label in key_map.items():
            if exif_key in tags:
                value = str(tags[exif_key])
                suspicious = False
                note = None

                if label == "Software":
                    suspicious, note = _flag_software(value)
                if label in ("Camera Make", "Camera Model"):
                    found_camera = True
                if label in ("GPS Latitude", "GPS Longitude"):
                    found_gps = True

                fields.append(MetadataField(key=label, value=value, suspicious=suspicious, note=note))

        if not found_camera and tags:
            fields.append(MetadataField(
                key="Camera Hardware",
                value="Not present",
                suspicious=True,
                note="No camera make/model in EXIF — real camera photos always include this"
            ))

    except Exception as e:
        fields.append(MetadataField(key="EXIF Error", value=str(e)))

    # Also try Pillow for image info
    try:
        from PIL import Image
        img = Image.open(file_path)
        fields.append(MetadataField(key="Format", value=img.format or "Unknown"))
        fields.append(MetadataField(key="Mode", value=img.mode))
        fields.append(MetadataField(key="Dimensions", value=f"{img.width} × {img.height} px"))
        if hasattr(img, "info"):
            for k, v in img.info.items():
                if isinstance(v, (str, int, float)) and k.lower() not in ("exif",):
                    label = k.replace("_", " ").title()
                    suspicious, note = _flag_software(str(v)) if "software" in k.lower() or "comment" in k.lower() else (False, None)
                    fields.append(MetadataField(key=label, value=str(v)[:200], suspicious=suspicious, note=note or None))
    except Exception:
        pass

    return fields


async def _extract_audio_metadata(file_path: Path) -> List[MetadataField]:
    fields: List[MetadataField] = []
    try:
        from mutagen import File as MutagenFile
        audio = MutagenFile(file_path)
        if audio is None:
            fields.append(MetadataField(key="Audio Tags", value="None found", suspicious=True))
            return fields

        fields.append(MetadataField(key="Duration", value=f"{audio.info.length:.2f} seconds"))
        if hasattr(audio.info, "bitrate"):
            fields.append(MetadataField(key="Bitrate", value=f"{audio.info.bitrate} bps"))
        if hasattr(audio.info, "sample_rate"):
            fields.append(MetadataField(key="Sample Rate", value=f"{audio.info.sample_rate} Hz"))
        if hasattr(audio.info, "channels"):
            fields.append(MetadataField(key="Channels", value=str(audio.info.channels)))

        tag_map = {
            "TIT2": "Title", "TPE1": "Artist", "TALB": "Album",
            "TYER": "Year", "TENC": "Encoded By", "TSSE": "Encoding Software",
            "COMM": "Comment", "title": "Title", "artist": "Artist",
            "album": "Album", "encoder": "Encoder", "comment": "Comment",
        }
        for tag_key, label in tag_map.items():
            if tag_key in audio:
                value = str(audio[tag_key])
                if hasattr(audio[tag_key], "text"):
                    value = str(audio[tag_key].text[0])
                suspicious, note = _flag_software(value) if label in ("Encoded By", "Encoding Software", "Encoder") else (False, None)
                fields.append(MetadataField(key=label, value=value[:200], suspicious=suspicious, note=note or None))

        if not any(f.key in ("Title", "Artist", "Encoded By") for f in fields):
            fields.append(MetadataField(
                key="Audio Tags",
                value="Minimal metadata",
                suspicious=True,
                note="Synthetic audio often lacks standard tagging"
            ))
    except Exception as e:
        fields.append(MetadataField(key="Audio Metadata Error", value=str(e)))
    return fields


async def _extract_video_metadata(file_path: Path) -> List[MetadataField]:
    fields: List[MetadataField] = []
    # Basic container parse without ffprobe dependency
    try:
        size = file_path.stat().st_size
        fields.append(MetadataField(key="File Size", value=f"{size:,} bytes"))

        suffix = file_path.suffix.lower()
        if suffix == ".mp4":
            fields.extend(await _parse_mp4_metadata(file_path))
        else:
            fields.append(MetadataField(
                key="Video Container",
                value=suffix.lstrip(".").upper(),
                suspicious=False
            ))
    except Exception as e:
        fields.append(MetadataField(key="Video Metadata Error", value=str(e)))
    return fields


async def _parse_mp4_metadata(file_path: Path) -> List[MetadataField]:
    """Minimal MP4 box parser to extract creation time and encoder."""
    fields: List[MetadataField] = []
    try:
        with open(file_path, "rb") as f:
            data = f.read(min(65536, file_path.stat().st_size))

        # Look for 'ftyp' box brand
        idx = data.find(b"ftyp")
        if idx >= 4:
            brand = data[idx + 4:idx + 8].decode("ascii", errors="replace").strip()
            fields.append(MetadataField(key="MP4 Brand", value=brand))

        # Look for encoder string heuristically
        for marker in [b"\xa9too", b"\xa9swr", b"Encoder", b"encoder"]:
            idx = data.find(marker)
            if idx != -1:
                snippet = data[idx + len(marker):idx + len(marker) + 80]
                text = snippet.decode("utf-8", errors="replace").split("\x00")[0].strip()
                if text:
                    suspicious, note = _flag_software(text)
                    fields.append(MetadataField(key="Encoder", value=text, suspicious=suspicious, note=note or None))
                    break

    except Exception:
        pass
    return fields


async def _extract_pdf_metadata(file_path: Path) -> List[MetadataField]:
    fields: List[MetadataField] = []
    try:
        import PyPDF2
        with open(file_path, "rb") as f:
            reader = PyPDF2.PdfReader(f)
            info = reader.metadata
            num_pages = len(reader.pages)

        fields.append(MetadataField(key="Page Count", value=str(num_pages)))

        if info:
            meta_map = {
                "/Title": "Title",
                "/Author": "Author",
                "/Creator": "Creator",
                "/Producer": "Producer",
                "/CreationDate": "Created",
                "/ModDate": "Modified",
                "/Subject": "Subject",
                "/Keywords": "Keywords",
            }
            for pdf_key, label in meta_map.items():
                if pdf_key in info and info[pdf_key]:
                    value = str(info[pdf_key])
                    suspicious, note = _flag_software(value) if label in ("Creator", "Producer") else (False, None)
                    fields.append(MetadataField(key=label, value=value[:300], suspicious=suspicious, note=note or None))
        else:
            fields.append(MetadataField(
                key="PDF Metadata",
                value="None found",
                suspicious=True,
                note="Documents without author/creator metadata are unusual"
            ))

        image_pages = 0
        blank_text_pages = 0
        fontless_pages = 0
        for page in reader.pages[:20]:
            page_text = (page.extract_text() or "").strip()
            if not page_text:
                blank_text_pages += 1

            resources = page.get("/Resources")
            if resources and hasattr(resources, "get_object"):
                resources = resources.get_object()
            if not isinstance(resources, dict):
                continue

            fonts = resources.get("/Font")
            if fonts and hasattr(fonts, "get_object"):
                fonts = fonts.get_object()
            if not fonts:
                fontless_pages += 1

            xobj = resources.get("/XObject")
            if xobj and hasattr(xobj, "get_object"):
                xobj = xobj.get_object()
            if isinstance(xobj, dict):
                for obj in xobj.values():
                    if hasattr(obj, "get_object"):
                        obj = obj.get_object()
                    if isinstance(obj, dict) and obj.get("/Subtype") == "/Image":
                        image_pages += 1
                        break

        if image_pages:
            fields.append(MetadataField(key="Image Pages", value=str(image_pages)))
        if blank_text_pages:
            fields.append(MetadataField(
                key="Text Extraction",
                value=f"{blank_text_pages} page(s) without extractable text",
                suspicious=blank_text_pages >= max(1, num_pages // 2),
                note="Image-only or flattened PDFs often have little or no text layer"
            ))
        if fontless_pages:
            fields.append(MetadataField(
                key="Font Resources",
                value=f"{fontless_pages} page(s) without font resources",
                suspicious=fontless_pages >= max(1, num_pages // 2),
                note="Pages without fonts are often rasterized exports rather than authored text PDFs"
            ))
    except Exception as e:
        fields.append(MetadataField(key="PDF Error", value=str(e)))
    return fields


async def _extract_docx_metadata(file_path: Path) -> List[MetadataField]:
    fields: List[MetadataField] = []
    try:
        with zipfile.ZipFile(file_path) as zf:
            names = set(zf.namelist())
            core_root = ET.fromstring(zf.read("docProps/core.xml")) if "docProps/core.xml" in names else None
            app_root = ET.fromstring(zf.read("docProps/app.xml")) if "docProps/app.xml" in names else None
            document_xml = zf.read("word/document.xml") if "word/document.xml" in names else b""
            media_count = sum(1 for name in names if name.startswith("word/media/"))

        core_values = {}
        if core_root is not None:
            core_values = {child.tag.split("}")[-1]: (child.text or "").strip() for child in core_root}
            prop_map = [
                ("Author", core_values.get("creator")),
                ("Title", core_values.get("title")),
                ("Subject", core_values.get("subject")),
                ("Keywords", core_values.get("keywords")),
                ("Description", core_values.get("description")),
                ("Created", core_values.get("created")),
                ("Modified", core_values.get("modified")),
                ("Last Modified By", core_values.get("lastModifiedBy")),
                ("Revision", core_values.get("revision")),
                ("Category", core_values.get("category")),
            ]

            for label, value in prop_map:
                if value:
                    suspicious, note = _flag_software(value) if label in ("Author", "Description", "Keywords") else (False, None)
                    fields.append(MetadataField(key=label, value=str(value)[:300], suspicious=suspicious, note=note or None))

        app_values = {}
        if app_root is not None:
            app_values = {child.tag.split("}")[-1]: (child.text or "").strip() for child in app_root}
            for key in ("Application", "Template", "Pages", "Words", "Paragraphs", "TotalTime"):
                value = app_values.get(key)
                if value:
                    fields.append(MetadataField(key=key, value=value[:300]))

        paragraph_count = document_xml.count(b"<w:p")
        if paragraph_count:
            fields.append(MetadataField(key="Paragraph Count", value=str(paragraph_count)))
        if media_count:
            fields.append(MetadataField(key="Embedded Media", value=str(media_count)))

        extracted_text_words = len(ET.tostring(ET.fromstring(document_xml), encoding="unicode", method="text").split()) if document_xml else 0
        if extracted_text_words >= 80 and app_values.get("Words") == "0":
            fields.append(MetadataField(
                key="Word Count Metadata",
                value="0 despite substantial text",
                suspicious=True,
                note="Automated DOCX generators often leave app.xml counters at zero"
            ))
        if paragraph_count >= 10 and app_values.get("Paragraphs") == "0":
            fields.append(MetadataField(
                key="Paragraph Metadata",
                value="0 despite many paragraph nodes",
                suspicious=True,
                note="Package counters were not updated to match the document body"
            ))

        created = core_values.get("created")
        modified = core_values.get("modified")
        if created and modified and created == modified and created.startswith("2013-12-23"):
            fields.append(MetadataField(
                key="Template Timestamp",
                value=created,
                suspicious=True,
                note="This is the default python-docx template timestamp rather than a real edit history"
            ))

        if not core_values.get("creator") and not core_values.get("lastModifiedBy"):
            fields.append(MetadataField(
                key="Authorship",
                value="No author metadata",
                suspicious=True,
                note="Documents stripped of author info may have been generated or sanitized"
            ))

    except Exception as e:
        fields.append(MetadataField(key="DOCX Error", value=str(e)))
    return fields
